### ISSUE TITLE
Logga till fil

### ISSUE THREAD

**Issue by OckePocke** [LeafCoders/rosette#36]
Logga följande till fil:
- Konfigurerade parametrar så att man kan vara säker på att rätt konfiguration används
- Stacktraces vid exceptions
- Något mer?

**Comment by mahlbom** [comment]
Skulle vara bra med en error-nivå och en debug-nivå. 
* Error-nivå är "bara" Exception, mer eller mindre.
* Debug-nivå är gärna utskrifter av input, komunikation med databas och externa API:et
