### ISSUE TITLE
Release av Undervisning

### ISSUE THREAD

**Issue by OckePocke** [LeafCoders/rosette#37]
Följande är kvar att fixa innan vi kan köra igång med Undervisning:
### Före uppgradering
- [x] Exportera alla ljudfiler från tidigare predikningar
- [x] Exportera titel, datum, tema och talare för tidigare predikningar
- [x] Hjälpprogram (t.ex. klass i Rosette) för att importera ljudfiler och undervisningar i databasen
- [x] Bild för Övrigt-tema
- [x] Privat undervisningssida på hemsidan med Peltate i. Peka på dev-servern
- [x] Boka in datum för uppgradering
### Vid uppgradering
- [x] Backup på Rosette-databasen innan uppgradering
- [x] Uppgradera server till senaste version av Rosette
- [x] Skapa om indexes i Rosette-databasen
- [x] Importera undervisningar med ljudinspelning
- [x] Ställ om Peltate på hemsidan till att peka ut prod-server och gör den publik
- [ ] Ge rättigheter till personer

**Comment by mahlbom** [comment]
Det ser bra ut förutom "Peka på dev-servern" Jag skulle vilja undvika det. Går det inte att flytta det som behövs från dev till prod?

**Comment by OckePocke** [comment]
Prod har en gammal version av Rosette där inte undervisningsdelen finns med. Därför kör jag mot dev när jag vill testa "undervisnings-appen", som ska finnas på Palmate. Efter att vi uppgraderar prod (det behöver vi göra tillsammans) så kan vi peka om "undervisnings-appen" så att den pekar på prod. Appen ska inte vara synlig utan inloggning tills vi har bytt till prod.

**Comment by mahlbom** [comment]
Ok, jag fattade det som "köra igång med Undervisning" så tolkade jag det att det var Live.
